const Data=[
    {
        property:'brightness',
        cssval:'brightness',
        unit:'%',
        max:200,
        min:100
    },
    {
        property:'saturation',
        cssval:'saturate',
        unit:'%',
        max:100,
        min:0
    },
    {
        property:'blur',
        cssval:'blur',
        unit:'px',
        max:5,
        min:0
    },
    {
        property:'hue',
        cssval:'hue-rotate',
        unit:'deg',
        max:360,
        min:0
    },
    {
        property:'contrast',
        cssval:'contrast',
        unit:'%',
        max:100,
        min:0
    },
    {
        property:'opacity',
        cssval:'opacity',
        unit:'%',
        max:100,
        min:0
    },
    {
        property:'greyscale',
        cssval:'grayscale',
        unit:'%',
        max:100,
        min:0
    },
    {
        property:'sepia',
        cssval:'sepia',
        unit:'%',
        max:100,
        min:0
    }
];

export default Data;